import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'part1-foundations/intro',
        'part1-foundations/chapter1',
        'part1-foundations/chapter2',
        'part1-foundations/chapter3',
        'part1-foundations/chapter4',
        'part1-foundations/chapter5'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'part2-perception/chapter2',
        'part2-perception/chapter2_2',
        'part2-perception/chapter2_3',
        'part2-perception/chapter2_4',
        'part2-perception/chapter2_5',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'part3-cognition/chapter3',
        'part3-cognition/chapter3_2',
        'part3-cognition/chapter3_3',
        'part3-cognition/chapter3_4',
        'part3-cognition/chapter3_5',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'part4-action/chapter4_1',
        'part4-action/chapter4_2',
        'part4-action/chapter4_3',
        'part4-action/chapter4_4',
        'part4-action/chapter4_5',
      ],
    },
    {
      type: 'category',
      label: 'Part 5: Advanced Topics and Societal Impact',
      items: [
        'part5-advanced-topics/chapter_ethics',
        'part5-advanced-topics/chapter5_2',
        'part5-advanced-topics/chapter5_3',
        'part5-advanced-topics/chapter5_4',
        'part5-advanced-topics/chapter5_5',
      ],
    },
    // Retain original tutorial and extras categories if they are meant to be separate
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Extras',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
  ],
};

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */


export default sidebars;
